#!/usr/bin/env python3
"""Build ai_info/catalog.yaml from article Markdown metadata."""
from __future__ import annotations

import re
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "catalog.yaml"
ARTICLE_DIRS = (
    ROOT / "anthropic" / "engineering",
    ROOT / "openai" / "research",
)


def yaml_quote(value: str | None) -> str:
    if value is None:
        return "null"
    escaped = value.replace("\\", "\\\\").replace("'", "''")
    return f"'{escaped}'"


def parse_list(raw: str) -> list[str]:
    return [item.strip().lstrip("#") for item in raw.split() if item.strip()]


def parse_authors(raw: str | None) -> list[str]:
    if not raw:
        return []
    raw = raw.replace(" 等", "")
    parts = re.split(r",|、|，| and ", raw)
    return [part.strip() for part in parts if part.strip()]


def extract_metadata(path: Path) -> dict[str, object]:
    text = path.read_text(encoding="utf-8-sig")
    lines = text.splitlines()
    title = lines[0].lstrip("# ").strip() if lines else path.stem

    source_url = None
    authors_raw = None
    published_at = None
    retrieved_at = None
    tags: list[str] = []

    for line in lines[:12]:
        if "**原文链接**" in line:
            match = re.search(r"\((https?://[^)]+)\)", line)
            source_url = match.group(1) if match else None
        elif "**作者**" in line:
            authors_raw = line.split(":", 1)[-1].strip()
        elif "**发布日期**" in line:
            published_at = line.split(":", 1)[-1].strip()
        elif "**检索日期**" in line:
            retrieved_at = line.split(":", 1)[-1].strip()
        elif "**标签**" in line:
            tags = parse_list(line.split(":", 1)[-1])

    rel = path.relative_to(ROOT).as_posix()
    provider = rel.split("/", 1)[0]
    category = rel.split("/", 2)[1] if "/" in rel else ""
    return {
        "path": rel,
        "provider": provider,
        "category": category,
        "title": title,
        "source_url": source_url,
        "published_at": published_at,
        "retrieved_at": retrieved_at,
        "authors": parse_authors(authors_raw),
        "tags": tags,
        "review_status": "needs_review" if source_url else "missing_source",
    }


def iter_articles() -> list[Path]:
    paths: list[Path] = []
    for directory in ARTICLE_DIRS:
        if directory.exists():
            paths.extend(p for p in directory.glob("*.md") if p.name != "summary.md")
    return sorted(paths)


def render_catalog(articles: list[dict[str, object]]) -> str:
    lines = [
        "# Generated by scripts/build_catalog.py. Do not edit article entries by hand.",
        "version: 1",
        f"catalog_generated_at: {yaml_quote(date.today().isoformat())}",
        "articles:",
    ]
    for article in articles:
        lines.append(f"  - path: {yaml_quote(article['path'])}")
        for key in ("provider", "category", "title", "source_url", "published_at", "retrieved_at", "review_status"):
            lines.append(f"    {key}: {yaml_quote(article[key])}")
        lines.append("    authors:")
        authors = article["authors"]
        if authors:
            for author in authors:  # type: ignore[assignment]
                lines.append(f"      - {yaml_quote(author)}")
        else:
            lines[-1] = "    authors: []"
        lines.append("    tags:")
        tags = article["tags"]
        if tags:
            for tag in tags:  # type: ignore[assignment]
                lines.append(f"      - {yaml_quote(tag)}")
        else:
            lines[-1] = "    tags: []"
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    articles = [extract_metadata(path) for path in iter_articles()]
    CATALOG.write_text(render_catalog(articles), encoding="utf-8")
    print(f"Wrote {CATALOG.relative_to(ROOT)} with {len(articles)} articles")


if __name__ == "__main__":
    main()
