#!/usr/bin/env python3
"""Build ai_info/catalog.yaml from article Markdown metadata."""
from __future__ import annotations

import re
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "catalog.yaml"

# 扫描所有 provider 的文章文件。支持两种目录结构：
#   - {provider}/{category}/*.md  （如 anthropic/engineering/, openai/research/, google/deepmind/）
#   - {provider}/*.md             （扁平结构，如 meta/）
# 排除：scripts/、topics/、.trae/、.vscode/ 等非 provider 目录，以及 summary.md / README.md / AGENTS.md
EXCLUDED_TOP_DIRS = {"scripts", "topics", ".trae", ".vscode", ".git"}
EXCLUDED_FILENAMES = {"summary.md", "README.md", "AGENTS.md"}


def article_dirs() -> list[Path]:
    """动态发现所有 provider/category 目录。"""
    dirs: list[Path] = []
    for provider_dir in ROOT.iterdir():
        if not provider_dir.is_dir():
            continue
        if provider_dir.name in EXCLUDED_TOP_DIRS or provider_dir.name.startswith("."):
            continue
        # 检查 provider 下是否有子目录（category 结构）
        subdirs = [p for p in provider_dir.iterdir() if p.is_dir()]
        if subdirs:
            # {provider}/{category}/ 结构
            for category_dir in subdirs:
                dirs.append(category_dir)
        else:
            # {provider}/ 扁平结构（如 meta/）
            dirs.append(provider_dir)
    return sorted(dirs)


def yaml_quote(value: str | None) -> str:
    if value is None:
        return "null"
    escaped = value.replace("\\", "\\\\").replace("'", "''")
    return f"'{escaped}'"


def parse_list(raw: str) -> list[str]:
    return [item.strip().lstrip("#") for item in raw.split() if item.strip()]


def parse_authors(raw: str | None) -> list[str]:
    if not raw:
        return []
    raw = raw.replace(" 等", "")
    parts = re.split(r",|、|，| and ", raw)
    return [part.strip() for part in parts if part.strip()]


def extract_metadata(path: Path) -> dict[str, object]:
    text = path.read_text(encoding="utf-8-sig")
    lines = text.splitlines()
    title = lines[0].lstrip("# ").strip() if lines else path.stem

    source_url = None
    authors_raw = None
    published_at = None
    retrieved_at = None
    tags: list[str] = []

    for line in lines[:12]:
        if "**原文链接**" in line:
            match = re.search(r"\((https?://[^)]+)\)", line)
            source_url = match.group(1) if match else None
        elif "**作者**" in line:
            authors_raw = line.split(":", 1)[-1].strip()
        elif "**发布日期**" in line:
            published_at = line.split(":", 1)[-1].strip()
        elif "**检索日期**" in line:
            retrieved_at = line.split(":", 1)[-1].strip()
        elif "**标签**" in line:
            tags = parse_list(line.split(":", 1)[-1])

    rel = path.relative_to(ROOT).as_posix()
    parts = rel.split("/")
    provider = parts[0]
    # 如果路径有 3 段（provider/category/file），category 是 parts[1]
    # 如果只有 2 段（provider/file，扁平结构如 meta/），category 为空字符串
    category = parts[1] if len(parts) >= 3 else ""
    return {
        "path": rel,
        "provider": provider,
        "category": category,
        "title": title,
        "source_url": source_url,
        "published_at": published_at,
        "retrieved_at": retrieved_at,
        "authors": parse_authors(authors_raw),
        "tags": tags,
        "review_status": "needs_review" if source_url else "missing_source",
    }


def iter_articles() -> list[Path]:
    paths: list[Path] = []
    for directory in article_dirs():
        if directory.exists():
            paths.extend(
                p for p in directory.glob("*.md")
                if p.name not in EXCLUDED_FILENAMES
            )
    return sorted(paths)


def render_catalog(articles: list[dict[str, object]]) -> str:
    lines = [
        "# Generated by scripts/build_catalog.py. Do not edit article entries by hand.",
        "version: 1",
        f"catalog_generated_at: {yaml_quote(date.today().isoformat())}",
        "articles:",
    ]
    for article in articles:
        lines.append(f"  - path: {yaml_quote(article['path'])}")
        for key in ("provider", "category", "title", "source_url", "published_at", "retrieved_at", "review_status"):
            lines.append(f"    {key}: {yaml_quote(article[key])}")
        lines.append("    authors:")
        authors = article["authors"]
        if authors:
            for author in authors:  # type: ignore[assignment]
                lines.append(f"      - {yaml_quote(author)}")
        else:
            lines[-1] = "    authors: []"
        lines.append("    tags:")
        tags = article["tags"]
        if tags:
            for tag in tags:  # type: ignore[assignment]
                lines.append(f"      - {yaml_quote(tag)}")
        else:
            lines[-1] = "    tags: []"
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    articles = [extract_metadata(path) for path in iter_articles()]
    CATALOG.write_text(render_catalog(articles), encoding="utf-8")
    print(f"Wrote {CATALOG.relative_to(ROOT)} with {len(articles)} articles")


if __name__ == "__main__":
    main()
